Login
HardSign-Team/eventnet-frontend pull request #1
Opened 2022-03-25 12:07 UTC by MichailNonProgramer

2022-03-25 12:09 UTC, lapakota commented on src/register/Registration.tsx
> +        console.log(1323)
1337

2022-03-25 17:34 UTC, IvanSibirtsev requested changes
норм

2022-03-25 17:34 UTC, IvanSibirtsev commented on src/shared/GenderSelector.tsx
> +        }
1. sex или gender? где-то ты пишешь sex где-то gender.
2. давайте писать нормальный код, а не true/false вместо enum

2022-03-25 17:34 UTC, IvanSibirtsev commented on src/register/Registration.tsx
> +    };
?

2022-03-25 17:34 UTC, IvanSibirtsev commented on src/register/Registration.tsx
> +                <GenderSelector label='Укажите свой пол' classNameDiv='gender_selector' onChange={setGender}/>
так gender или пол?

2022-03-25 18:27 UTC, lapakota commented on src/shared/GenderSelector.tsx
> +        }
enum {
 true: true,
 false: false
}

2022-03-26 17:07 UTC, IvanSibirtsev requested changes

2022-03-26 17:07 UTC, IvanSibirtsev commented on src/register/Registration.tsx
> +            <Gapped gap={7} vertical className='form__registration'>
почему 7?

2022-03-26 17:08 UTC, lapakota commented on src/register/Registration.tsx
> +            <Gapped gap={7} vertical className='form__registration'>
Я так сказал🕶️

2022-03-26 17:12 UTC, lapakota commented on src/register/Registration.tsx
> +    };
?

2022-03-26 17:14 UTC, closed without merging